const ACTION_TYPES = {
  PROJECT: {
    CREATE_PROJECT: 'CREATE_PROJECT',
    CREATE_PROJECT_SUCCESS: 'CREATE_PROJECT_SUCCESS',
    UPDATE_PROJECT: 'UPDATE_PROJECT',
    UPDATE_PROJECT_SUCCESS: 'UPDATE_PROJECT_SUCCESS',
    DELETE_PROJECT: 'DELETE_PROJECT',
    CALCULATE_PROJECT: 'CALCULATE_PROJECT',
    LOAD_PROJECT_BYSLUG: 'LOAD_PROJECT_BYSLUG',
    LOAD_PROJECT_BYSLUG_SUCCESS: 'LOAD_PROJECT_BYSLUG_SUCCESS',
    LOAD_PROJECT_FLOW: 'LOAD_PROJECT_FLOW',
    LOAD_PROJECT_FLOW_SUCCESS: 'LOAD_PROJECT_FLOW_SUCCESS',
    LOAD_PROJECT_INFO: 'LOAD_PROJECT_INFO',
    LOAD_PROJECT_INFO_SUCCESS: 'LOAD_PROJECT_INFO_SUCCESS'
  },
  BUDGET: {
    CREATE_BUDGET: 'CREATE_BUDGET',
    UPDATE_BUDGET: 'UPDATE_BUDGET',
    DELETE_BUDGET: 'DELETE_BUDGET',
    LOAD_BUDGET: 'LOAD_BUDGET',
    CALCULATE_BUDGET: 'CALCULATE_BUDGET'
  },
  QUOTATION: {
    CREATE_QUOTATION: 'CREATE_QUOTATION',
    UPDATE_QUOTATION: 'UPDATE_QUOTATION',
    DELETE_QUOTATION: 'DELETE_QUOTATION',
    LOAD_QUOTATION: 'LOAD_QUOTATION',
    CALCULATE_QUOTATION: 'CALCULATE_QUOTATION'
  },
  USER: {
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
    SAVE_CURRENT_USER: 'SAVE_CURRENT_USER',
    REMOVE_CURRENT_USER: 'REMOVE_CURRENT_USER',
    EXIST_CURRENT_USER: 'EXIST_CURRENT_USER',
    EXIST_CURRENT_USER_SUCCESSFUL: 'EXIST_CURRENT_USER_SUCCESS'
  },
  PORTFOLIO: {
    CALCULATE_PORTFOLIO: 'CALCULATE_PORTFOLIO',
    LOAD_PORTFOLIO_FLOW: 'LOAD_PORTFOLIO_FLOW',
    LOAD_PORTFOLIO_FLOW_SUCCESS: 'LOAD_PORTFOLIO_FLOW_SUCCESS',
    LOAD_PORTFOLIO_INFO: 'LOAD_PORTFOLIO_INFO',
    LOAD_PORTFOLIO_INFO_SUCCESS: 'LOAD_PORTFOLIO_INFO_SUCCESS'
  },
  PEOPLE: {
    ADD_USER_TO_PROJECT: 'ADD_USER_TO_PROJECT',
    ADD_USER_TO_PROJECT_SUCCESS: 'ADD_USER_TO_PROJECT_SUCCESS',
    REMOVE_USER_FROM_PROJECT: 'REMOVE_USER_FROM_PROJECT'
  },
  AUTH: {
    IS_LOGGED: 'IS_LOGGED'
  },
  API: {
    BEGIN_API_CALL: 'BEGIN_API_CALL',
    ERROR_API_CALL: 'ERROR_API_CALL'
  },
  ERROR: {
    LOG_ERROR: 'LOG_ERROR',
    REMOVE_ERROR: 'REMOVE_ERROR'
  },
  DEFAULT: 'DEFAULT'
}

/* All delete operations are by default optimistic deletes */
/* All calculate operations are by default optimistic calculations */

export default ACTION_TYPES;